import RPi.GPIO as GPIO

import pigpio

PIGPIO  = pigpio.pi()

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

PIN_SAVEUR_1 = 4
PIN_SAVEUR_2 = 17
PIN_SAVEUR_3 = 22
PIN_SAVEUR_4 = 23
PIN_SAVEUR_5 = 9
PIN_EAU = 8




GPIO.setup(PIN_SAVEUR_1, GPIO.OUT)
GPIO.setup(PIN_SAVEUR_2, GPIO.OUT)
GPIO.setup(PIN_SAVEUR_3, GPIO.OUT)
GPIO.setup(PIN_SAVEUR_4, GPIO.OUT)
GPIO.setup(PIN_SAVEUR_5, GPIO.OUT)
GPIO.setup(PIN_EAU, GPIO.OUT)


GPIO.output(PIN_SAVEUR_1, GPIO.HIGH)
GPIO.output(PIN_SAVEUR_2, GPIO.HIGH)
GPIO.output(PIN_SAVEUR_3, GPIO.HIGH)
GPIO.output(PIN_SAVEUR_4, GPIO.HIGH)
GPIO.output(PIN_SAVEUR_5, GPIO.HIGH)
GPIO.output(PIN_EAU , GPIO.HIGH)